# Generated by Django 3.1.12 on 2022-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UberAi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='phone_number',
            field=models.CharField(default=212698549160, max_length=20),
            preserve_default=False,
        ),
    ]
